FROM node:26-alpine AS builder

WORKDIR /app

COPY microservices/file-process/package*.json ./
RUN npm install

COPY microservices/file-process/ ./
COPY shared /shared

RUN mkdir -p src/shared/file-processing \
    && cp -R /shared/file-processing/. src/shared/file-processing/

RUN npm run build

FROM node:26-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/main.js"]
