FROM node:26-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/main/package.json ./apps/main/
COPY apps/file-process/package.json ./apps/file-process/
COPY apps/rag/package.json ./apps/rag/
COPY packages/shared/logger/package.json ./packages/shared/logger/
COPY packages/shared/rabbitmq/package.json ./packages/shared/rabbitmq/
COPY packages/shared/firebase/package.json ./packages/shared/firebase/
COPY packages/shared/file-storage/package.json ./packages/shared/file-storage/
COPY packages/shared/qdrant/package.json ./packages/shared/qdrant/
COPY packages/contracts/file-process/package.json ./packages/contracts/file-process/
COPY packages/contracts/rag/package.json ./packages/contracts/rag/
COPY configs ./configs

RUN npm ci

COPY . .

ENV DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/app_db"

RUN npm run build:dependencies --workspace=@vention/main

RUN npm run prisma:generate --workspace=@vention/main

RUN npm run build --workspace=@vention/main

FROM node:26-alpine AS runner

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/apps/main/package.json ./apps/main/
COPY --from=builder /app/apps/main/dist ./apps/main/dist
COPY --from=builder /app/apps/main/prisma ./apps/main/prisma
COPY --from=builder /app/apps/main/src/config ./apps/main/src/config
COPY --from=builder /app/apps/main/src/generated ./apps/main/src/generated

WORKDIR /app/apps/main

CMD ["sh", "-c", "npx prisma migrate deploy --config src/config/prisma/prisma.config.ts && node dist/src/main"]
